services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: ubuntu
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydb

    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          cpus: "0.3" # Limit to 30% of 1 vCPU
          memory: 500M # Reduced from 500M
        reservations:
          memory: 100M # Reserve minimum memory
    networks:
      - gate-tier

  nginx:
    restart: always
    build:
      context: "./nginx"
    ports:
      - "443:443"
    deploy:
      resources:
        limits:
          cpus: "0.2" # Limit to 20% of 1 vCPU
          memory: 50M # Already appropriate
        reservations:
          memory: 20M
    networks:
      - gate-tier

  # backend:
  #   restart: always
  #   command:
  #     - pnpm -F backend run prisma
  #     - pnpm -F backend run dev
  #   environment:
  #     DATABASE_URL: mysql://ubuntu:password@db:3306/mydb
  #     PORT: "8080"
  #   build:
  #     dockerfile: ./backend.Dockerfile
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "0.3" # Limit to 30% of 1 vCPU
  #         memory: 150M # Reduced from 200M
  #       reservations:
  #         memory: 50M
  #   networks:
  #     - gate-tier

volumes:
  mysql-data:

networks:
  gate-tier:
