services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: ubuntu
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydb
    # ports:
    #   - "3306:3306" # Maps host port 3306 to container port 3306
    # expose:
    #   - 3306

    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
    deploy:
      resources:
        limits:
          memory: 400M
    networks:
      - backend

  nginx:
    hostname: nginx
    restart: always
    build:
      context: "./nginx"
    # volumes:
    #   - ./nginx/conf.d/:/etc/nginx/conf.d/
    #   - ./nginx/log:/var/log/nginx/
    ports:
      - "443:443"
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 50M
    networks:
      - backend

  backend:
    hostname: backend
    restart: always
    command: npm run serve
    environment:
      DATABASE_URL: mysql://root:password@db:3306/mydb
      PORT: "8080"
    # volumes:
    #   - ./:/usr/src/app
    build:
      context: "./packages/backend"
    deploy:
      resources:
        limits:
          memory: 300M
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.123.0/24
