services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: ubuntu
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydb

    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - 3306
    deploy:
      resources:
        limits:
          cpus: "0.3" # Limit to 30% of 1 vCPU
          memory: 500M # Reduced from 500M
        reservations:
          memory: 100M # Reserve minimum memory

  nginx:
    restart: always
    build:
      context: "./nginx"
    ports:
      - "443:443"
    deploy:
      resources:
        limits:
          cpus: "0.2" # Limit to 20% of 1 vCPU
          memory: 50M # Already appropriate
        reservations:
          memory: 20M
    network_mode: host  # Use host network to access localhost:8080


volumes:
  mysql-data:

