name: GitHub Actions CICD
run-name: ${{ github.actor }} deploy make-appointment 🚀
on:
  push:
    branches:
      - "main"
  paths:
    - "packages/backend/**" # Trigger only when files in packages/backend change
    # - "ansible/**"          # Include ansible files if changes there should also trigger
    # - "docker-compose.yml"  # Include docker-compose.yml if relevant to backend deployment
jobs:
  Ansible-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"
          config: |
            Host aws
              HostName ${{ secrets.SSH_HOST }}
              CheckHostIP no
              User ubuntu
              Port 22

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: run ansible
        run: |
          cd ansible && ansible-playbook update.yml
